.vibeapp/
└── .streamlit/
    └── secrets.toml
# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
